import {
    REJECT_SAVE,
    REJECT_OPEN,
    RESOLVE_IMPORT_PUBLICATIONS,
    REJECT_IMPORT_PUBLICATIONS,
    RESOLVE_IMPORT_DOIS,
    REJECT_IMPORT_DOIS,
    RESOLVE_IMPORT_BIBTEX,
    REJECT_IMPORT_BIBTEX,
    SELECT_GRAPH_DISPLAY,
    SELECT_LIST_DISPLAY,
    PUBLICATION_FROM_DOI,
    RESOLVE_PUBLICATION_FROM_DOI,
    REJECT_PUBLICATION_FROM_DOI,
    ADD_PUBLICATION_TO_COLLECTION,
    SELECT_PUBLICATION,
    UNSELECT_PUBLICATION,
    REMOVE_PUBLICATION,
    UPDATE_PUBLICATION,
    UPDATE_ALL_PUBLICATIONS,
    RESOLVE_SCHOLAR_INITIAL_REQUEST,
    RESOLVE_SCHOLAR_CITERS_REQUEST,
    REJECT_SCHOLAR_CITERS_REQUEST,
    REJECT_SCHOLAR_CITER_PARSING,
    SET_SCHOLAR_REQUEST_REFRACTORY_PERIOD,
    RESOLVE_BIBTEX_FROM_DOI,
    RESOLVE_PUBLICATION_FROM_CITER_METADATA,
    RESOLVE_PUBLICATION_FROM_IMPORTED_METADATA,
    REJECT_PUBLICATION_FROM_METADATA,
    REMOVE_WARNING,
    REMOVE_ALL_WARNINGS,
    SELECT_TAB,
    SET_GRAPH_THRESHOLD,
    SET_GRAPH_ZOOM_AND_OFFSET,
    ENABLE_STICKY_GRAPH,
    DISABLE_STICKY_GRAPH,
    STORE_GRAPH_NODES,
    LOCK_GRAPH_NODE,
    RELEASE_GRAPH_NODE,
    SET_SEARCH,
} from '../constants/actionTypes'

export default function menu(state = 0, action) {
    switch (action.type) {
        case REJECT_SAVE:
        case REJECT_OPEN:
        case RESOLVE_IMPORT_PUBLICATIONS:
        case REJECT_IMPORT_PUBLICATIONS:
        case RESOLVE_IMPORT_DOIS:
        case REJECT_IMPORT_DOIS:
        case RESOLVE_IMPORT_BIBTEX:
        case REJECT_IMPORT_BIBTEX:
        case SELECT_GRAPH_DISPLAY:
        case SELECT_LIST_DISPLAY:
        case PUBLICATION_FROM_DOI:
        case RESOLVE_PUBLICATION_FROM_DOI:
        case REJECT_PUBLICATION_FROM_DOI:
        case ADD_PUBLICATION_TO_COLLECTION:
        case SELECT_PUBLICATION:
        case UNSELECT_PUBLICATION:
        case REMOVE_PUBLICATION:
        case UPDATE_PUBLICATION:
        case UPDATE_ALL_PUBLICATIONS:
        case RESOLVE_SCHOLAR_INITIAL_REQUEST:
        case RESOLVE_SCHOLAR_CITERS_REQUEST:
        case REJECT_SCHOLAR_CITERS_REQUEST:
        case REJECT_SCHOLAR_CITER_PARSING:
        case SET_SCHOLAR_REQUEST_REFRACTORY_PERIOD:
        case RESOLVE_BIBTEX_FROM_DOI:
        case RESOLVE_PUBLICATION_FROM_CITER_METADATA:
        case RESOLVE_PUBLICATION_FROM_IMPORTED_METADATA:
        case REJECT_PUBLICATION_FROM_METADATA:
        case REMOVE_WARNING:
        case REMOVE_ALL_WARNINGS:
        case SELECT_TAB:
        case SET_GRAPH_THRESHOLD:
        case SET_GRAPH_ZOOM_AND_OFFSET:
        case ENABLE_STICKY_GRAPH:
        case DISABLE_STICKY_GRAPH:
        case STORE_GRAPH_NODES:
        case LOCK_GRAPH_NODE:
        case RELEASE_GRAPH_NODE:
        case SET_SEARCH:
            return state + 1;
        default:
            return state;
    }
}
