export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';

export const RESET = 'RESET';
export const OPEN_MENU_ITEM = 'OPEN_MENU_ITEM';
export const CLOSE_MENU = 'CLOSE_MENU';
export const RESOLVE_SAVE = 'RESOLVE_SAVE';
export const REJECT_SAVE = 'REJECT_SAVE';
export const REJECT_OPEN = 'REJECT_OPEN';
export const RESOLVE_IMPORT_PUBLICATIONS = 'RESOLVE_IMPORT_PUBLICATIONS';
export const REJECT_IMPORT_PUBLICATIONS = 'REJECT_IMPORT_PUBLICATIONS';
export const RESOLVE_IMPORT_BIBTEX = 'RESOLVE_IMPORT_BIBTEX';
export const REJECT_IMPORT_BIBTEX = 'REJECT_IMPORT_BIBTEX';
export const SELECT_GRAPH_DISPLAY = 'SELECT_GRAPH_DISPLAY';
export const SELECT_LIST_DISPLAY = 'SELECT_LIST_DISPLAY'

export const PUBLICATION_FROM_DOI = 'PUBLICATION_FROM_DOI';
export const FETCH_PUBLICATION_FROM_DOI = 'FETCH_PUBLICATION_FROM_DOI';
export const RESOLVE_PUBLICATION_FROM_DOI = 'RESOLVE_PUBLICATION_FROM_DOI';
export const REJECT_PUBLICATION_FROM_DOI = 'REJECT_PUBLICATION_FROM_DOI';
export const REJECT_PUBLICATION_FROM_DOI_CONNECTION = 'REJECT_PUBLICATION_FROM_DOI_CONNECTION';

export const BIBTEX_FROM_DOI = 'BIBTEX_FROM_DOI';
export const FETCH_BIBTEX_FROM_DOI = 'FETCH_BIBTEX_FROM_DOI';
export const RESOLVE_BIBTEX_FROM_DOI = 'RESOLVE_BIBTEX_FROM_DOI';
export const REJECT_BIBTEX_FROM_DOI = 'REJECT_BIBTEX_FROM_DOI';
export const REJECT_BIBTEX_FROM_DOI_CONNECTION = 'REJECT_BIBTEX_FROM_DOI_CONNECTION';

export const ADD_PUBLICATION_TO_COLLECTION = 'ADD_PUBLICATION_TO_COLLECTION';
export const SELECT_PUBLICATION = 'SELECT_PUBLICATION';
export const UNSELECT_PUBLICATION = 'UNSELECT_PUBLICATION';
export const REMOVE_PUBLICATION = 'REMOVE_PUBLICATION';
export const UPDATE_PUBLICATION = 'UPDATE_PUBLICATION';
export const UPDATE_ALL_PUBLICATIONS = 'UPDATE_ALL_PUBLICATIONS';

export const FETCH_SCHOLAR_PAGE = 'FETCH_SCHOLAR_PAGE';
export const RESOLVE_SCHOLAR_INITIAL_PAGE = 'RESOLVE_SCHOLAR_INITIAL_PAGE';
export const RESOLVE_SCHOLAR_CITERS_PAGE = 'RESOLVE_SCHOLAR_CITERS_PAGE';
export const REJECT_SCHOLAR_CONNECTION = 'REJECT_SCHOLAR_CONNECTION';
export const REJECT_SCHOLAR_CITERS_PAGE = 'REJECT_SCHOLAR_CITERS_PAGE';
export const REJECT_SCHOLAR_CITER_PARSING = 'REJECT_SCHOLAR_CITER_PARSING';
export const SCHOLAR_PAGE_REFRACTORY_PERIOD_DONE = 'SCHOLAR_PAGE_REFRACTORY_PERIOD_DONE';
export const SET_SCHOLAR_PAGE_REFRACTORY_PERIOD = 'SET_SCHOLAR_PAGE_REFRACTORY_PERIOD';
export const BLOCK_SCHOLAR = 'BLOCK_SCHOLAR';
export const UNBLOCK_SCHOLAR = 'UNBLOCK_SCHOLAR';
export const RESET_SCHOLAR = 'RESET_SCHOLAR';
export const CHANGE_RECAPTCHA_VISIBILITY = 'CHANGE_RECAPTCHA_VISIBILITY';
export const SCHOLAR_DISCONNECT = 'SCHOLAR_DISCONNECT';

export const PUBLICATION_FROM_CITER_METADATA = 'PUBLICATION_FROM_CITER_METADATA';
export const PUBLICATION_FROM_IMPORTED_METADATA = 'PUBLICATION_FROM_IMPORTED_METADATA';
export const FETCH_PUBLICATION_FROM_METADATA = 'FETCH_PUBLICATION_FROM_METADATA';
export const RESOLVE_PUBLICATION_FROM_CITER_METADATA = 'RESOLVE_PUBLICATION_FROM_CITER_METADATA';
export const RESOLVE_PUBLICATION_FROM_IMPORTED_METADATA = 'RESOLVE_PUBLICATION_FROM_IMPORTED_METADATA';
export const REJECT_PUBLICATION_FROM_METADATA = 'REJECT_PUBLICATION_FROM_METADATA';
export const REJECT_PUBLICATION_FROM_METADATA_CONNECTION = 'REJECT_PUBLICATION_FROM_METADATA_CONNECTION';

export const REMOVE_WARNING = 'REMOVE_WARNING';
export const REMOVE_ALL_WARNINGS = 'REMOVE_ALL_WARNINGS';

export const SELECT_TAB = 'SELECT_TAB';

export const SET_SEARCH = 'SET_SEARCH';

export const SET_GRAPH_THRESHOLD = 'SET_GRAPH_THRESHOLD';
export const SET_GRAPH_ZOOM_AND_OFFSET = 'SET_GRAPH_ZOOM_AND_OFFSET';
export const ENABLE_STICKY_GRAPH = 'ENABLE_STICKY_GRAPH';
export const DISABLE_STICKY_GRAPH = 'DISABLE_STICKY_GRAPH';
export const STORE_GRAPH_NODES = 'STORE_GRAPH_NODES';
export const LOCK_GRAPH_NODE = 'LOCK_GRAPH_NODE';
export const RELEASE_GRAPH_NODE = 'RELEASE_GRAPH_NODE';

export const ACQUIRE_MOUSE = 'ACQUIRE_MOUSE';
export const RELEASE_MOUSE = 'RELEASE_MOUSE';
