export const PUBLICATION_STATUS_UNVALIDATED = "PUBLICATION_STATUS_UNVALIDATED";
export const PUBLICATION_STATUS_DEFAULT = "PUBLICATION_STATUS_DEFAULT";
export const PUBLICATION_STATUS_IN_COLLECTION =
    "PUBLICATION_STATUS_IN_COLLECTION";

export const SCHOLAR_REQUEST_TYPE_INITIALIZE =
    "SCHOLAR_REQUEST_TYPE_INITIALIZE";
export const SCHOLAR_REQUEST_TYPE_CITERS = "SCHOLAR_REQUEST_TYPE_CITERS";

export const SCHOLAR_STATUS_IDLE = "SCHOLAR_STATUS_IDLE";
export const SCHOLAR_STATUS_FETCHING = "SCHOLAR_STATUS_FETCHING";
export const SCHOLAR_STATUS_BLOCKED_HIDDEN = "SCHOLAR_STATUS_BLOCKED_HIDDEN";
export const SCHOLAR_STATUS_BLOCKED_VISIBLE = "SCHOLAR_STATUS_BLOCKED_VISIBLE";
export const SCHOLAR_STATUS_UNBLOCKING = "SCHOLAR_STATUS_UNBLOCKING";

export const CROSSREF_REQUEST_TYPE_VALIDATION =
    "CROSSREF_REQUEST_TYPE_VALIDATION";
export const CROSSREF_REQUEST_TYPE_CITER_METADATA =
    "CROSSREF_REQUEST_TYPE_CITER_METADATA";
export const CROSSREF_REQUEST_TYPE_IMPORTED_METADATA =
    "CROSSREF_REQUEST_TYPE_IMPORTED_METADATA";

export const CROSSREF_STATUS_IDLE = "CROSSREF_STATUS_IDLE";
export const CROSSREF_STATUS_FETCHING = "CROSSREF_STATUS_FETCHING";
