export const PUBLICATION_STATUS_UNVALIDATED = 'PUBLICATION_STATUS_UNVALIDATED';
export const PUBLICATION_STATUS_DEFAULT = 'PUBLICATION_STATUS_DEFAULT';
export const PUBLICATION_STATUS_IN_COLLECTION = 'PUBLICATION_STATUS_IN_COLLECTION';

export const PAGE_TYPE_INITIALIZE = 'PAGE_TYPE_INITIALIZE';
export const PAGE_TYPE_CITERS = 'PAGE_TYPE_CITERS';

export const PUBLICATION_REQUEST_TYPE_CITER_METADATA = 'PUBLICATION_REQUEST_TYPE_CITER_METADATA';
export const PUBLICATION_REQUEST_TYPE_IMPORTED_METADATA = 'PUBLICATION_REQUEST_TYPE_IMPORTED_METADATA';

export const SCHOLAR_STATUS_IDLE = 'SCHOLAR_STATUS_IDLE';
export const SCHOLAR_STATUS_FETCHING = 'SCHOLAR_STATUS_FETCHING';
export const SCHOLAR_STATUS_BLOCKED_HIDDEN = 'SCHOLAR_STATUS_BLOCKED_HIDDEN';
export const SCHOLAR_STATUS_BLOCKED_VISIBLE = 'SCHOLAR_STATUS_BLOCKED_VISIBLE';
export const SCHOLAR_STATUS_UNBLOCKING = 'SCHOLAR_STATUS_UNBLOCKING';
